services:
  api-gateway:
    build: .
    container_name: api-gateway
    depends_on:
      - redis_rate_limiter
    environment:
      REDIS_HOST: redis_rate_limiter
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - global-network
  
  redis_rate_limiter:
    image: redis:latest
    container_name: redis_rate_limiter
    ports:
      - "6380:6379"  
    networks:
      - global-network  

networks:
  global-network:
    external: true  # Usa un network Docker già esistente

volumes:
  route_db_data: